"""new fields in user model


Revision ID: 894070e0dc43
Revises: 1ca9434b47fd
Create Date: 2018-04-03 21:12:38.185430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894070e0dc43'
down_revision = '1ca9434b47fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
